/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import clases.Insumo;

import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import javax.swing.text.*;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.*;
import controlador.Controlador;
import PDF.PDF;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import modelo.Modelo;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hector
 */
public class frmInventarioReporte extends javax.swing.JFrame {
    DefaultTableModel dtm;
String pdfFilePath = "D:\\ONEDRIVEHECTORUTP\\OneDrive - Universidad Tecnologica del Peru\\Reportes PDF";
File file = new File(pdfFilePath);

    /**
     * Creates new form frmReporte
     */
    
   
    
    public frmInventarioReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnReporte = new javax.swing.JButton();
        btnGenerarReportePDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Buscar");

        jButton1.setText("Buscar");

        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Insumos Por agotarse", "unidades Restantes"
            }
        ));
        jScrollPane1.setViewportView(tableModel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Insumos por Vencer", "Dias Restantes para su vencimiento"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnReporte.setText("Generar Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        btnGenerarReportePDF.setText("Generar Reporte PDF");
        btnGenerarReportePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReportePDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReporte)
                .addGap(36, 36, 36)
                .addComponent(btnGenerarReportePDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReporte)
                            .addComponent(btnGenerarReportePDF))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(214, 214, 214))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
      // Crear una instancia del modelo para obtener los insumos
    Modelo modelo = new Modelo();
    
    // Obtener la lista de insumos desde la base de datos
        ArrayList<Insumo> insumos;
        insumos = new ArrayList<>();
    
    // Crear el modelo de tabla para mostrar los insumos
    DefaultTableModel tableModel = new DefaultTableModel();
    tableModel.addColumn("Código Insumo");
    tableModel.addColumn("Nombre Insumo");
    tableModel.addColumn("Cantidad Insumo");
    tableModel.addColumn("Categoría Insumo");
    
    // Rellenar el modelo de tabla con los datos de los insumos
    for (Insumo insumo : insumos) {
        Object[] rowData = {
            insumo.getCodigo(),
            insumo.getNombre(),
            insumo.getCantidad(),
            insumo.getCategoria()
        };
        tableModel.addRow(rowData);
    }
    
    // Asignar el modelo a un JTable (o cualquier componente de tabla que uses)
    JTable table = new JTable(tableModel);
    
    // Mostrar el reporte en un JScrollPane para poder visualizar la tabla
    JScrollPane scrollPane = new JScrollPane(table);
    JFrame reporteFrame = new JFrame("Reporte de Inventario");
    reporteFrame.getContentPane().add(scrollPane);
    reporteFrame.setSize(600, 400); // Ajustar el tamaño del frame
    reporteFrame.setVisible(true); // Hacer visible la ventana con el reporte
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnGenerarReportePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReportePDFActionPerformed
        // TODO add your handling code here:
           // Obtener los insumos desde la base de datos
      Modelo modelo = new Modelo();
    List<Insumo> insumos = new ArrayList<>();
      
    
    
    modelo.getInsumos();
    
    // Definir el nombre del archivo PDF
    String pdfFilePath = "Reporte_Inventario_ZariSpa.pdf";
    
    // Crear el documento PDF
    Document document = new Document();
    try {
        // Crear escritor de PDF
        PdfWriter.getInstance(document, new FileOutputStream(pdfFilePath));
        
        // Abrir el documento
        document.open();
        
        // Añadir título al PDF
        document.add(new Paragraph("D:\\ONEDRIVEHECTORUTP\\OneDrive - Universidad Tecnologica del Peru\\Reportes PDF"));
        document.add(new Paragraph("Fecha: " + new java.util.Date()));
        document.add(new Paragraph(" "));
        
        // Crear tabla con 4 columnas (correspondientes a los datos de la tabla INVENTARIO)
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        
        // Añadir los encabezados de la tabla
        table.addCell("Código");
        table.addCell("Nombre");
        table.addCell("Cantidad");
        table.addCell("Categoría");
        
        // Añadir los datos de los insumos
        for (Insumo insumo : insumos) {
            table.addCell(insumo.getCodigo());
            table.addCell(insumo.getNombre());
            table.addCell(String.valueOf(insumo.getCantidad()));
            table.addCell(insumo.getCategoria());
        }
        
        // Añadir la tabla al documento PDF
        document.add(table);
        
        // Cerrar el documento
        document.close();
        
        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Reporte PDF generado exitosamente en " + pdfFilePath);
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al generar el reporte PDF: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGenerarReportePDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventarioReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventarioReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventarioReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventarioReporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventarioReporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReportePDF;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tableModel;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
